// Adult self-report reflex questionnaire catalog (`adult_v3`).
// German item wording and reflex mappings are taken verbatim from
// Reflexprofil_Erwachsenenfragebogen_adult_v3_Arbeitsfassung.
// Filter `f_*` wording is app-owned (plan §5.3) and marked expertPending.
// English is a professional translation of the same meaning.
//
// ignore_for_file: lines_longer_than_80_chars

import 'reflex_questionnaire.dart';

const _r = _AdultReflexRefs();

/// Versioned adult questionnaire used for self-report from age 16.
final adultSelfQuestionnaireV3 = ReflexQuestionnaireDefinition(
  id: 'adult_self_reflex_profile',
  version: 'adult_v3',
  type: ReflexQuestionnaireType.adultSelfReport,
  titleDe: 'Reflexprofil für Erwachsene',
  titleEn: 'Reflex Profile for Adults',
  screenTitleDe: 'Reflexprofil',
  screenTitleEn: 'Reflex Profile',
  // Unused by AdultReflexProfileScoringService (Phase 4). Required by the
  // shared definition type; child thresholds must not be read for adult UI.
  scoring: const ReflexScoringDefinition(
    strongPercent: 100,
    elevatedPercent: 80,
    indicationPercent: 50,
  ),
  questions: [
    _filter(
      "f_swim",
      1,
      textDe: "Hast du Schwimmerfahrung?",
      textEn: "Do you have swimming experience?",
      providesFilter: ApplicabilityFilter.swims,
    ),
    _filter(
      "f_screen",
      2,
      textDe: "Arbeitest du regelmäßig am Bildschirm?",
      textEn: "Do you regularly work at a screen?",
      providesFilter: ApplicabilityFilter.screenWork,
    ),
    _filter(
      "f_desk",
      3,
      textDe: "Arbeitest du regelmäßig am Schreibtisch?",
      textEn: "Do you regularly work at a desk?",
      providesFilter: ApplicabilityFilter.deskWork,
    ),
    _filter(
      "f_drive",
      4,
      textDe: "Fährst du selbst Auto?",
      textEn: "Do you drive a car yourself?",
      providesFilter: ApplicabilityFilter.drives,
    ),
    _filter(
      "f_passenger",
      5,
      textDe: "Sitzt du regelmäßig als Mitfahrer:in im Auto?",
      textEn: "Do you regularly sit as a passenger in a car?",
      providesFilter: ApplicabilityFilter.ridesAsPassenger,
    ),
    _filter(
      "f_handwriting",
      6,
      textDe: "Schreibst du regelmäßig von Hand?",
      textEn: "Do you regularly write by hand?",
      providesFilter: ApplicabilityFilter.handwriting,
    ),
    _filter(
      "f_tools",
      7,
      textDe: "Nutzt du regelmäßig Werkzeuge (z. B. Schere, Schraubendreher)?",
      textEn: "Do you regularly use tools (for example scissors or a screwdriver)?",
      providesFilter: ApplicabilityFilter.toolUse,
    ),
    _score(
      "s013",
      8,
      AdultQuestionModule.sensory,
      textDe: "Sind deine Fußsohlen so empfindlich oder kitzelig, dass du Berührungen dort ungern zulässt – etwa bei Fußpflege, Massage oder beim Schuhkauf?",
      textEn: "Are the soles of your feet so sensitive or ticklish that you prefer not to have them touched — for example during foot care, massage or when buying shoes?",
      reflexes: [_r.babinski, _r.plantar],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s014",
      9,
      AdultQuestionModule.sensory,
      textDe: "Bist du am Körper ungewöhnlich kitzelig, besonders am Rücken oder an den Seiten?",
      textEn: "Are you unusually ticklish on your body, especially on your back or sides?",
      reflexes: [_r.spinalGalant],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s034",
      10,
      AdultQuestionModule.sensory,
      textDe: "Empfindest du alltägliche Geräusche – etwa Staubsauger, Händetrockner oder Stimmengewirr – deutlich lauter oder unangenehmer als Menschen um dich herum?",
      textEn: "Do you experience everyday noises — such as vacuum cleaners, hand dryers or overlapping voices — as clearly louder or more unpleasant than people around you?",
      reflexes: [_r.moro, _r.flr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s035",
      11,
      AdultQuestionModule.sensory,
      textDe: "Empfindest du alltägliche Helligkeit oder Lichtquellen häufig als deutlich unangenehmer als Menschen um dich herum?",
      textEn: "Do you often experience everyday brightness or light sources as clearly more unpleasant than people around you?",
      reflexes: [_r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s036",
      12,
      AdultQuestionModule.sensory,
      textDe: "Sind leichte Berührungen an Armen, Nacken oder Kopf für dich häufig unangenehm, auch wenn sie von vertrauten Menschen kommen?",
      textEn: "Are light touches on your arms, neck or head often unpleasant for you, even when they come from people you trust?",
      reflexes: [_r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s087",
      13,
      AdultQuestionModule.sensory,
      textDe: "Meidest du enge Kleidung oder feste Bündchen, weil sie sich besonders am Rücken oder an der Taille schnell unangenehm anfühlen?",
      textEn: "Do you avoid tight clothing or firm waistbands because they quickly feel unpleasant, especially on your back or waist?",
      reflexes: [_r.spinalGalant],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a004",
      14,
      AdultQuestionModule.sensory,
      textDe: "Wirst du bei vielen gleichzeitigen Reizen – Stimmen, Musik und Bewegung – eher still oder wie abgeschaltet, statt gereizt zu reagieren?",
      textEn: "When many stimuli happen at once — voices, music and movement — do you tend to go quiet or shut down rather than react irritably?",
      reflexes: [_r.flr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a011",
      15,
      AdultQuestionModule.sensory,
      textDe: "Hast du beim Konzentrieren häufig etwas im oder am Mund zu tun – etwa Kaugummi kauen, auf einen Stift oder die Wange beißen?",
      textEn: "When concentrating, do you often need something in or around your mouth — for example chewing gum, biting a pen or your cheek?",
      reflexes: [_r.babkin],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s001",
      16,
      AdultQuestionModule.postureSitting,
      textDe: "Stehst du häufig mit deutlich nach innen gedrehten Füßen?",
      textEn: "Do you often stand with your feet clearly turned inward?",
      reflexes: [_r.flr, _r.babinski],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s004",
      17,
      AdultQuestionModule.postureSitting,
      textDe: "Krallst du beim Stehen, Gehen oder Konzentrieren deine Zehen merklich ein?",
      textEn: "When standing, walking or concentrating, do you noticeably curl your toes?",
      reflexes: [_r.plantar],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s008",
      18,
      AdultQuestionModule.postureSitting,
      textDe: "Verhakst du beim Sitzen häufig die Füße an den Stuhlbeinen oder legst ein Bein unter dich?",
      textEn: "When sitting, do you often hook your feet around the chair legs or tuck one leg under yourself?",
      reflexes: [_r.stnr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s009",
      19,
      AdultQuestionModule.postureSitting,
      textDe: "Neigst du beim Zuhören oder Beobachten den Kopf häufig nach unten und schaust dabei von unten nach oben?",
      textEn: "When listening or watching, do you often tip your head downward and look up from below?",
      reflexes: [_r.tlr, _r.stnr, _r.righting],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s012",
      20,
      AdultQuestionModule.postureSitting,
      textDe: "Lehnst du dich beim Sitzen selten an die Rückenlehne an, obwohl eine vorhanden ist?",
      textEn: "Do you rarely lean against the backrest when sitting, even when one is available?",
      reflexes: [_r.spinalGalant, _r.landau],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s015",
      21,
      AdultQuestionModule.postureSitting,
      textDe: "Hast du deutlich ausgeprägte X- oder O-Beine?",
      textEn: "Do you have clearly pronounced knock-knees or bow legs?",
      reflexes: [_r.babinski],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s017",
      22,
      AdultQuestionModule.postureSitting,
      textDe: "Hast du beim Sitzen oder Bewegen wiederkehrende Hüftbeschwerden oder auffällige Bewegungseinschränkungen der Hüfte?",
      textEn: "Do you have recurring hip discomfort when sitting or moving, or noticeable limitations of hip movement?",
      reflexes: [_r.spinalGalant, _r.stnr, _r.amphibian],
      polarity: ReflexItemPolarity.direct,
      approvalStatus: ReflexContentApprovalStatus.expertPending,
    ),
    _score(
      "s018",
      23,
      AdultQuestionModule.postureSitting,
      textDe: "Hast du häufig Rückenschmerzen, die nicht nur nach einer ungewohnten Belastung auftreten?",
      textEn: "Do you often have back pain that does not only appear after unusual strain?",
      reflexes: [_r.flr, _r.rootingSucking],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s019",
      24,
      AdultQuestionModule.postureSitting,
      textDe: "Wurde bei dir ärztlich eine Skoliose festgestellt?",
      textEn: "Have you been medically diagnosed with scoliosis?",
      reflexes: [_r.spinalGalant],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s020",
      25,
      AdultQuestionModule.postureSitting,
      textDe: "Ist dein oberer Rücken deutlich nach vorn gerundet oder fällt es dir schwer, dich dort aufzurichten?",
      textEn: "Is your upper back clearly rounded forward, or is it hard for you to straighten up there?",
      reflexes: [_r.stnr, _r.landau],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a018",
      26,
      AdultQuestionModule.postureSitting,
      textDe: "Wird dein Nacken einseitig fest oder müde, wenn du länger mit gedrehtem Kopf arbeitest oder sitzt?",
      textEn: "Does one side of your neck become tight or tired when you work or sit for longer with your head turned?",
      reflexes: [_r.atnr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a021",
      27,
      AdultQuestionModule.postureSitting,
      textDe: "Suchst du beim längeren Stehen häufig etwas zum Anlehnen oder Abstützen – etwa eine Wand, einen Tresen oder Türrahmen?",
      textEn: "When standing for longer, do you often look for something to lean or brace against — for example a wall, counter or door frame?",
      reflexes: [_r.landau, _r.righting],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s022",
      28,
      AdultQuestionModule.motorCoordination,
      textDe: "Falls du es sicher weißt: Hast du als Kleinkind das Krabbeln ausgelassen?",
      textEn: "If you know this for certain: did you skip crawling as a toddler?",
      reflexes: [_r.stnr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s023",
      29,
      AdultQuestionModule.motorCoordination,
      textDe: "Gehst du heute häufig auf Zehenspitzen, ohne dass Schuhe, Sport oder eine Verletzung der Grund sind?",
      textEn: "Do you often walk on tiptoe today, without shoes, sport or an injury being the reason?",
      reflexes: [_r.tlr, _r.stnr, _r.landau, _r.plantar],
      polarity: ReflexItemPolarity.direct,
      approvalStatus: ReflexContentApprovalStatus.expertPending,
    ),
    _score(
      "s024",
      30,
      AdultQuestionModule.motorCoordination,
      textDe: "Fällt dir oder anderen auf, dass du beim Gehen deutlich schief gehst oder eine Seite anders belastest?",
      textEn: "Do you or others notice that you walk clearly unevenly or load one side differently?",
      reflexes: [_r.spinalGalant],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s025",
      31,
      AdultQuestionModule.motorCoordination,
      textDe: "Fällt es dir schwer, eine feste Faust zu machen, obwohl Hand oder Finger nicht akut verletzt sind?",
      textEn: "Is it hard for you to make a firm fist, even though your hand or fingers are not acutely injured?",
      reflexes: [_r.babkin],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s026",
      32,
      AdultQuestionModule.motorCoordination,
      textDe: "Brauchst du beim Anziehen von Socken oder Schuhen auffällig viele Anläufe oder musst du dich dafür besonders abstützen?",
      textEn: "When putting on socks or shoes, do you need noticeably many attempts or have to brace yourself specially?",
      reflexes: [_r.plantar],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s028",
      33,
      AdultQuestionModule.motorCoordination,
      textDe: "Rutschst du beim längeren Sitzen häufig nach vorn, streckst die Beine aus und lässt den Kopf nach vorne sinken?",
      textEn: "When sitting for longer, do you often slide forward, stretch your legs out and let your head sink forward?",
      reflexes: [_r.tlr, _r.stnr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s029",
      34,
      AdultQuestionModule.motorCoordination,
      textDe: "Hast du Mühe, einen langsam und gut sichtbar zugeworfenen Ball zu fangen?",
      textEn: "Do you find it hard to catch a ball that is thrown slowly and clearly visible?",
      reflexes: [_r.moro, _r.tlr, _r.atnr, _r.stnr],
      polarity: ReflexItemPolarity.direct,
      approvalStatus: ReflexContentApprovalStatus.expertPending,
    ),
    _score(
      "s030",
      35,
      AdultQuestionModule.motorCoordination,
      textDe: "Fiel oder fällt dir Brustschwimmen deutlich schwerer als andere Schwimmarten?",
      textEn: "Is or was breaststroke clearly harder for you than other swimming strokes?",
      reflexes: [_r.stnr, _r.landau],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.swims},
    ),
    _score(
      "s032",
      36,
      AdultQuestionModule.motorCoordination,
      textDe: "Hast du Schwierigkeiten, dich in neuen Gebäuden zurechtzufinden?",
      textEn: "Do you have difficulty finding your way in unfamiliar buildings?",
      reflexes: [_r.tlr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a025",
      37,
      AdultQuestionModule.workScreenFocus,
      textDe: "Ermüdet dich der häufige Blickwechsel zwischen Bildschirm und Papier stärker als das Lesen selbst?",
      textEn: "Does frequent glancing between screen and paper tire you more than reading itself?",
      reflexes: [_r.atnr, _r.stnr],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.screenWork},
    ),
    _score(
      "a027",
      38,
      AdultQuestionModule.workScreenFocus,
      textDe: "Stellst du den Bildschirm bewusst genau mittig vor dich, weil seitliches Arbeiten dich schnell ermüdet oder verspannt?",
      textEn: "Do you deliberately place the screen exactly centred in front of you because working to the side quickly tires or strains you?",
      reflexes: [_r.atnr],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.screenWork},
    ),
    _score(
      "a033",
      39,
      AdultQuestionModule.workScreenFocus,
      textDe: "Reißt dich fast jedes Nebengeräusch aus der Konzentration, auch wenn es leise ist?",
      textEn: "Does almost every background noise pull you out of concentration, even when it is quiet?",
      reflexes: [_r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a036",
      40,
      AdultQuestionModule.workScreenFocus,
      textDe: "Arbeitest du deutlich lieber im Stehen oder mit stark erhöhtem Bildschirm, weil Sitzen am Schreibtisch dich schneller ermüdet?",
      textEn: "Do you clearly prefer working while standing or with a strongly raised screen because sitting at a desk tires you more quickly?",
      reflexes: [_r.stnr, _r.landau],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.deskWork},
    ),
    _score(
      "s086",
      41,
      AdultQuestionModule.drivingOrientationTravel,
      textDe: "Wird dir beim Reisen im Auto, Bus, Zug oder auf dem Schiff vergleichsweise schnell übel?",
      textEn: "When travelling by car, bus, train or ship, do you get nauseous comparatively quickly?",
      reflexes: [_r.flr, _r.moro, _r.tlr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a040",
      42,
      AdultQuestionModule.drivingOrientationTravel,
      textDe: "Drehst du beim Schulterblick den Oberkörper deutlich mit, statt überwiegend nur den Kopf zu drehen?",
      textEn: "When looking over your shoulder, do you turn your upper body clearly as well instead of mostly turning only your head?",
      reflexes: [_r.atnr],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.drives},
    ),
    _score(
      "a042",
      43,
      AdultQuestionModule.drivingOrientationTravel,
      textDe: "Suchst du lieber einen weiter entfernten Parkplatz, auf den du vorwärts fahren kannst, statt rückwärts einzuparken?",
      textEn: "Do you prefer a more distant parking space you can drive into forwards rather than reverse parking?",
      reflexes: [_r.atnr],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.drives},
    ),
    _score(
      "a043",
      44,
      AdultQuestionModule.drivingOrientationTravel,
      textDe: "Wird dir als Mitfahrer schnell unwohl oder übel, sobald du auf ein Handy, Buch oder eine Karte schaust?",
      textEn: "As a passenger, do you quickly feel unwell or nauseous as soon as you look at a phone, book or map?",
      reflexes: [_r.tlr],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.ridesAsPassenger},
    ),
    _score(
      "a049",
      45,
      AdultQuestionModule.drivingOrientationTravel,
      textDe: "Verlierst du in großen, ähnlich aussehenden Gebäuden – Klinik, Kaufhaus oder Parkhaus – schnell die Orientierung?",
      textEn: "In large buildings that look similar — hospital, department store or car park — do you quickly lose your bearings?",
      reflexes: [_r.tlr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s101",
      46,
      AdultQuestionModule.sportBalanceFeet,
      textDe: "Sind deine Socken regelmäßig zuerst an der großen Zehe durchgelaufen?",
      textEn: "Do your socks regularly wear through first at the big toe?",
      reflexes: [_r.babinski, _r.plantar],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a052",
      47,
      AdultQuestionModule.sportBalanceFeet,
      textDe: "Wirst du mit Schuhen auf unebenem Grund – Kopfsteinpflaster, Wiese oder Schotter – deutlich langsamer und vorsichtiger als Begleitpersonen?",
      textEn: "On uneven ground in shoes — cobblestones, grass or gravel — do you become clearly slower and more cautious than people with you?",
      reflexes: [_r.righting],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a057",
      48,
      AdultQuestionModule.sportBalanceFeet,
      textDe: "Ermüdet dein Rücken bei vorgebeugten Tätigkeiten – Gartenarbeit, Bettbeziehen oder Spülmaschine – schneller als Arme oder Beine?",
      textEn: "During bent-forward tasks — gardening, making a bed or unloading a dishwasher — does your back tire faster than your arms or legs?",
      reflexes: [_r.landau],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a058",
      49,
      AdultQuestionModule.sportBalanceFeet,
      textDe: "Wird dir unsicher oder flau, wenn du im Stehen den Kopf weit in den Nacken legst?",
      textEn: "Do you feel unsteady or queasy when you tip your head far back while standing?",
      reflexes: [_r.tlr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a092",
      50,
      AdultQuestionModule.sportBalanceFeet,
      textDe: "Bekommst du in Ruhe oder nachts wiederholt Krämpfe in Füßen oder Zehen?",
      textEn: "Do you repeatedly get cramps in your feet or toes at rest or at night?",
      reflexes: [_r.plantar],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a095",
      51,
      AdultQuestionModule.sportBalanceFeet,
      textDe: "Verändert sich deine Beinstellung bei Müdigkeit sichtbar – fallen die Knie dann stärker nach innen oder außen?",
      textEn: "Does your leg alignment change visibly when you are tired — do the knees then fall more inward or outward?",
      reflexes: [_r.babinski],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s057",
      52,
      AdultQuestionModule.speechMouthJaw,
      textDe: "Hast du eine deutliche Zahnfehlstellung oder einen ungewöhnlich hohen und schmalen Gaumen?",
      textEn: "Do you have a clear dental misalignment or an unusually high and narrow palate?",
      reflexes: [_r.babkin, _r.rootingSucking],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s058",
      53,
      AdultQuestionModule.speechMouthJaw,
      textDe: "Knirschst du wiederholt mit den Zähnen, besonders nachts oder in Belastungssituationen?",
      textEn: "Do you repeatedly grind your teeth, especially at night or in stressful situations?",
      reflexes: [_r.babkin, _r.rootingSucking],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s059",
      54,
      AdultQuestionModule.speechMouthJaw,
      textDe: "Hast du als Kind über das fünfte Lebensjahr hinaus regelmäßig am Daumen gelutscht?",
      textEn: "As a child, did you regularly suck your thumb beyond the age of five?",
      reflexes: [_r.babkin, _r.rootingSucking],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s060",
      55,
      AdultQuestionModule.speechMouthJaw,
      textDe: "Hast du auch außerhalb von Essen oder Sport einen auffällig starken Speichelfluss?",
      textEn: "Outside of eating or sport, do you have noticeably strong saliva flow?",
      reflexes: [_r.babkin, _r.rootingSucking],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s061",
      56,
      AdultQuestionModule.speechMouthJaw,
      textDe: "Machst du beim Schreiben unwillkürlich Mund- oder Zungenbewegungen?",
      textEn: "When writing, do you make involuntary mouth or tongue movements?",
      reflexes: [_r.babkin, _r.plantar, _r.palmar],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.handwriting},
    ),
    _score(
      "s062",
      57,
      AdultQuestionModule.speechMouthJaw,
      textDe: "Beißt du beim Konzentrieren häufig die Zähne fest zusammen?",
      textEn: "When concentrating, do you often clench your teeth tightly?",
      reflexes: [_r.babkin, _r.plantar, _r.palmar],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s063",
      58,
      AdultQuestionModule.speechMouthJaw,
      textDe: "Wird dir häufiger zurückgemeldet, dass du undeutlich sprichst oder bestimmte Laute schwer verständlich aussprichst?",
      textEn: "Are you often told that you speak unclearly or that certain sounds are hard to understand?",
      reflexes: [_r.stnr, _r.babkin, _r.plantar, _r.palmar, _r.rootingSucking],
      polarity: ReflexItemPolarity.direct,
      approvalStatus: ReflexContentApprovalStatus.expertPending,
    ),
    _score(
      "a010",
      59,
      AdultQuestionModule.speechMouthJaw,
      textDe: "Meidest du bestimmte Speisen wegen ihrer Beschaffenheit im Mund – körnig, faserig oder schleimig – unabhängig vom Geschmack?",
      textEn: "Do you avoid certain foods because of how they feel in your mouth — grainy, fibrous or slimy — regardless of taste?",
      reflexes: [_r.rootingSucking],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a094",
      60,
      AdultQuestionModule.speechMouthJaw,
      textDe: "Verschluckst du dich beim Essen oder Trinken häufiger als Menschen um dich herum?",
      textEn: "Do you choke on food or drink more often than people around you?",
      reflexes: [_r.rootingSucking],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s066",
      61,
      AdultQuestionModule.writingFineMotor,
      textDe: "Hältst du den Stift beim Schreiben auffällig fest oder verkrampft?",
      textEn: "When writing, do you hold the pen unusually tightly or in a cramped way?",
      reflexes: [_r.babkin, _r.palmar, _r.righting],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.handwriting},
    ),
    _score(
      "s068",
      62,
      AdultQuestionModule.writingFineMotor,
      textDe: "Drückst du beim Schreiben so fest auf, dass sich die Schrift auf der Rückseite des Blattes abzeichnet?",
      textEn: "When writing, do you press so hard that the writing shows through on the back of the page?",
      reflexes: [_r.righting, _r.palmar],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.handwriting},
    ),
    _score(
      "s069",
      63,
      AdultQuestionModule.writingFineMotor,
      textDe: "Meidest du Handschrift selbst dann, wenn eine kurze handschriftliche Notiz schneller wäre?",
      textEn: "Do you avoid handwriting even when a short handwritten note would be faster?",
      reflexes: [_r.stnr, _r.righting, _r.palmar],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.handwriting},
    ),
    _score(
      "s070",
      64,
      AdultQuestionModule.writingFineMotor,
      textDe: "Schmerzt oder versteift deine Schreibhand beim Schreiben vergleichsweise schnell?",
      textEn: "Does your writing hand hurt or stiffen comparatively quickly while writing?",
      reflexes: [_r.stnr, _r.righting, _r.palmar],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.handwriting},
    ),
    _score(
      "s072",
      65,
      AdultQuestionModule.writingFineMotor,
      textDe: "Ist deine Handschrift für andere häufig schwer lesbar?",
      textEn: "Is your handwriting often hard for others to read?",
      reflexes: [_r.spinalGalant, _r.stnr, _r.babkin, _r.righting],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.handwriting},
      approvalStatus: ReflexContentApprovalStatus.expertPending,
    ),
    _score(
      "s073",
      66,
      AdultQuestionModule.writingFineMotor,
      textDe: "Drehst du beim Schreiben das Blatt deutlich schräg oder quer vor dich?",
      textEn: "When writing, do you turn the page clearly at an angle or sideways in front of you?",
      reflexes: [_r.atnr],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.handwriting},
    ),
    _score(
      "s074",
      67,
      AdultQuestionModule.writingFineMotor,
      textDe: "Verrutschen deine Zeilen auf unliniertem Papier deutlich nach oben oder unten?",
      textEn: "On unlined paper, do your lines clearly drift up or down?",
      reflexes: [_r.atnr],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.handwriting},
    ),
    _score(
      "a068",
      68,
      AdultQuestionModule.writingFineMotor,
      textDe: "Bleibt deine Hand nach längerem Werkzeuggebrauch – Schere, Schraubendreher oder Gartenschere – steif oder verkrampft?",
      textEn: "After longer tool use — scissors, screwdriver or garden shears — does your hand stay stiff or cramped?",
      reflexes: [_r.palmar],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.toolUse},
    ),
    _score(
      "a074",
      69,
      AdultQuestionModule.writingFineMotor,
      textDe: "Gehst du beim Schreiben mit dem Kopf sehr dicht an das Papier heran?",
      textEn: "When writing, do you bring your head very close to the paper?",
      reflexes: [_r.stnr],
      polarity: ReflexItemPolarity.direct,
      requiresFilters: {ApplicabilityFilter.handwriting},
    ),
    _contextItem(
      "s078",
      70,
      AdultQuestionModule.readingLearningOrientation,
      textDe: "Wurde bei dir eine Lese-Rechtschreib-Schwäche festgestellt?",
      textEn: "Have you been diagnosed with a reading and spelling difficulty?",
    ),
    _contextItem(
      "s079",
      71,
      AdultQuestionModule.readingLearningOrientation,
      textDe: "Wurde bei dir Dyskalkulie festgestellt?",
      textEn: "Have you been diagnosed with dyscalculia?",
    ),
    _contextItem(
      "s082",
      72,
      AdultQuestionModule.readingLearningOrientation,
      textDe: "Fällt dir Lernen insgesamt schwer?",
      textEn: "Do you find learning difficult overall?",
    ),
    _score(
      "s080",
      73,
      AdultQuestionModule.readingLearningOrientation,
      textDe: "Ermüdest du beim Lesen vergleichsweise schnell?",
      textEn: "Do you tire comparatively quickly when reading?",
      reflexes: [_r.flr, _r.moro, _r.stnr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s081",
      74,
      AdultQuestionModule.readingLearningOrientation,
      textDe: "Verlierst du beim Lesen häufig die Zeile, lässt Wörter aus oder liest deutlich langsamer als für dich üblich?",
      textEn: "When reading, do you often lose the line, skip words or read clearly more slowly than usual for you?",
      reflexes: [_r.flr, _r.atnr, _r.stnr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s084",
      75,
      AdultQuestionModule.readingLearningOrientation,
      textDe: "Kannst du dir neue Informationen häufig nur schwer merken, obwohl du aufmerksam warst?",
      textEn: "Do you often find it hard to remember new information even though you were paying attention?",
      reflexes: [_r.spinalGalant, _r.landau],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s090",
      76,
      AdultQuestionModule.readingLearningOrientation,
      textDe: "Fällt es dir schwer einzuschätzen, wie viel Zeit vergangen ist oder wie lange eine Aufgabe dauern wird?",
      textEn: "Is it hard for you to estimate how much time has passed or how long a task will take?",
      reflexes: [_r.tlr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a029",
      77,
      AdultQuestionModule.readingLearningOrientation,
      textDe: "Häufen sich bei langen Texten gegen Ende Buchstabendreher oder Fehler bei einfachen Wörtern?",
      textEn: "In long texts, do letter reversals or mistakes with simple words pile up toward the end?",
      reflexes: [_r.atnr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s038",
      78,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Erlebst du Trennungssituationen oder das Alleinsein häufig als ungewöhnlich belastend?",
      textEn: "Do you often experience separation situations or being alone as unusually stressful?",
      reflexes: [_r.flr, _r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s039",
      79,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Wirst du unter Belastung vergleichsweise schnell sehr emotional oder musst weinen?",
      textEn: "Under strain, do you become very emotional comparatively quickly or need to cry?",
      reflexes: [_r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s040",
      80,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Wirst du bei kleinen Auslösern vergleichsweise schnell gereizt oder wütend?",
      textEn: "With small triggers, do you become irritated or angry comparatively quickly?",
      reflexes: [_r.moro, _r.atnr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s041",
      81,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Fällt es dir schwer, Aufgaben, Termine oder Dinge im Alltag zu organisieren?",
      textEn: "Is it hard for you to organise tasks, appointments or everyday things?",
      reflexes: [_r.spinalGalant],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s044",
      82,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Verlierst du dich so häufig in Tagträumen, dass du Aufgaben oder Gespräche aus dem Blick verlierst?",
      textEn: "Do you get lost in daydreams so often that you lose track of tasks or conversations?",
      reflexes: [_r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s050",
      83,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Schränken starke Ängste vor bestimmten Situationen oder Dingen deinen Alltag ein?",
      textEn: "Do strong fears of certain situations or things restrict your everyday life?",
      reflexes: [_r.flr, _r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s051",
      84,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Erschrickst du bei plötzlichen Geräuschen oder Bewegungen deutlich stärker als Menschen um dich herum?",
      textEn: "Do sudden noises or movements startle you clearly more strongly than people around you?",
      reflexes: [_r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s052",
      85,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Belasten dich kurzfristige Planänderungen stärker, als du es selbst angemessen findest?",
      textEn: "Do short-notice plan changes stress you more than you yourself find reasonable?",
      reflexes: [_r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s053",
      86,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Gehst du Auseinandersetzungen häufig aus dem Weg, obwohl dir dadurch ein Nachteil entsteht?",
      textEn: "Do you often avoid confrontations even when that puts you at a disadvantage?",
      reflexes: [_r.moro, _r.flr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s055",
      87,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Fällt es dir schwer, dich zwischen ähnlich guten Möglichkeiten zu entscheiden, selbst wenn die Folgen klein sind?",
      textEn: "Is it hard for you to choose between similarly good options, even when the consequences are small?",
      reflexes: [_r.moro, _r.flr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "s100",
      88,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Hält dich geringes Vertrauen in die eigenen Fähigkeiten häufig davon ab, etwas zu beginnen oder zu sagen?",
      textEn: "Does low confidence in your own abilities often stop you from starting something or speaking up?",
      reflexes: [_r.flr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a076",
      89,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Wirst du in einem Streit häufig still oder wie blockiert, statt weiter sprechen zu können?",
      textEn: "In an argument, do you often go quiet or feel blocked instead of being able to keep talking?",
      reflexes: [_r.flr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a077",
      90,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Schiebst du gerade wichtige Aufgaben wiederholt auf, obwohl dir daraus Nachteile entstehen?",
      textEn: "Do you repeatedly put off important tasks even though that creates disadvantages for you?",
      reflexes: [_r.flr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a079",
      91,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Bereitest du alltägliche Gespräche – Arzttermin, Reklamation oder Rückfrage – vorher innerlich nahezu wörtlich vor?",
      textEn: "Do you prepare everyday conversations — a doctor appointment, a complaint or a follow-up question — almost word for word in your mind beforehand?",
      reflexes: [_r.flr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a082",
      92,
      AdultQuestionModule.behaviorStressEmotion,
      textDe: "Ziehst du dich nach belastenden Tagen häufig zurück und wirst still, statt dich auszutauschen?",
      textEn: "After stressful days, do you often withdraw and go quiet instead of talking things through?",
      reflexes: [_r.flr],
      polarity: ReflexItemPolarity.direct,
    ),
    _contextItem(
      "s099",
      93,
      AdultQuestionModule.sleepDigestionBody,
      textDe: "Hast du wiederkehrende Verdauungsbeschwerden?",
      textEn: "Do you have recurring digestive complaints?",
    ),
    _score(
      "s102",
      94,
      AdultQuestionModule.sleepDigestionBody,
      textDe: "Hast du deine Pubertät rückblickend als ungewöhnlich schwierig oder körperlich stark belastend erlebt?",
      textEn: "Looking back, did you experience puberty as unusually difficult or physically very stressful?",
      reflexes: [_r.amphibian],
      polarity: ReflexItemPolarity.direct,
      approvalStatus: ReflexContentApprovalStatus.expertPending,
    ),
    _score(
      "a088",
      95,
      AdultQuestionModule.sleepDigestionBody,
      textDe: "Zuckst du beim Einschlafen häufig mit dem ganzen Körper zusammen?",
      textEn: "When falling asleep, do you often jerk with your whole body?",
      reflexes: [_r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a089",
      96,
      AdultQuestionModule.sleepDigestionBody,
      textDe: "Kannst du fast nur in einer bestimmten Kopfhaltung ruhig schlafen?",
      textEn: "Can you sleep calmly in almost only one specific head position?",
      reflexes: [_r.tlr],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a090",
      97,
      AdultQuestionModule.sleepDigestionBody,
      textDe: "Reagiert dein Verdauungssystem deutlich auf Anspannung – etwa mit Bauchdrücken oder Durchfall vor belastenden Terminen?",
      textEn: "Does your digestive system react clearly to tension — for example with stomach pressure or diarrhoea before stressful appointments?",
      reflexes: [_r.moro],
      polarity: ReflexItemPolarity.direct,
    ),
    _score(
      "a096",
      98,
      AdultQuestionModule.sleepDigestionBody,
      textDe: "Ist das Liegen auf dem Bauch für deinen unteren Rücken unangenehm?",
      textEn: "Is lying on your stomach uncomfortable for your lower back?",
      reflexes: [_r.landau],
      polarity: ReflexItemPolarity.direct,
    ),
    _safety(
      "s046",
      99,
      textDe: "Wurde bei dir ADHS oder ADS festgestellt?",
      textEn: "Have you been diagnosed with ADHD or ADD?",
      reflexes: [_r.atnr, _r.stnr],
      warningRule: ReflexWarningRule.professionalClearanceRequired,
    ),
    _safety(
      "s094",
      100,
      textDe: "Hast du Epilepsie?",
      textEn: "Do you have epilepsy?",
      reflexes: const <PrimitiveReflex>[],
      warningRule: ReflexWarningRule.professionalClearanceRequired,
    ),
    _safety(
      "s095",
      101,
      textDe: "Wurde bei dir Autismus oder eine Autismus-Spektrum-Zuordnung festgestellt?",
      textEn: "Have you been diagnosed with autism or an autism spectrum classification?",
      reflexes: const <PrimitiveReflex>[],
      warningRule: ReflexWarningRule.professionalClearanceRequired,
    ),
    _safety(
      "s096",
      102,
      textDe: "Hast du Trisomie 21 (Down-Syndrom)?",
      textEn: "Do you have Trisomy 21 (Down syndrome)?",
      reflexes: const <PrimitiveReflex>[],
      warningRule: ReflexWarningRule.professionalClearanceRequired,
    ),
    _safety(
      "s097",
      103,
      textDe: "Bist du derzeit in psychologischer oder psychiatrischer Begleitung?",
      textEn: "Are you currently in psychological or psychiatric care?",
      reflexes: const <PrimitiveReflex>[],
      warningRule: ReflexWarningRule.professionalClearanceRequired,
    ),
    _safety(
      "s098",
      104,
      textDe: "Bist du schwanger?",
      textEn: "Are you pregnant?",
      reflexes: const <PrimitiveReflex>[],
      warningRule: ReflexWarningRule.professionalClearanceRequired,
    ),
    _safety(
      "a126",
      105,
      textDe: "Neigst du aktuell zu Schwindel oder Ohnmacht?",
      textEn: "Do you currently tend to feel dizzy or faint?",
      reflexes: const <PrimitiveReflex>[],
      warningRule: ReflexWarningRule.professionalClearanceRequired,
    ),
    _safety(
      "a127",
      106,
      textDe: "Hattest du kürzlich eine Operation oder eine noch nicht ausgeheilte Verletzung?",
      textEn: "Have you recently had surgery or an injury that has not yet fully healed?",
      reflexes: const <PrimitiveReflex>[],
      warningRule: ReflexWarningRule.professionalClearanceRequired,
    ),
    _safety(
      "a128",
      107,
      textDe: "Hattest du einen Bandscheibenvorfall oder eine Operation an der Wirbelsäule?",
      textEn: "Have you had a disc herniation or surgery on the spine?",
      reflexes: const <PrimitiveReflex>[],
      warningRule: ReflexWarningRule.professionalClearanceRequired,
    ),
    _safety(
      "a129",
      108,
      textDe: "Hast du Herz-Kreislauf-Beschwerden, die bei Bewegung relevant sein könnten?",
      textEn: "Do you have cardiovascular symptoms that could be relevant during movement?",
      reflexes: const <PrimitiveReflex>[],
      warningRule: ReflexWarningRule.professionalClearanceRequired,
    ),
    _movement(
      "s005",
      109,
      textDe: "Kannst du mit geöffneten Augen sicher auf einem Bein stehen?",
      textEn: "Can you stand safely on one leg with your eyes open?",
      reflexes: [_r.flr, _r.moro, _r.tlr, _r.atnr, _r.babinski],
      polarity: ReflexItemPolarity.inverse,
      requiresFilters: {ApplicabilityFilter.afterSafetyCleared},
      approvalStatus: ReflexContentApprovalStatus.expertPending,
    ),
    _movement(
      "s006",
      110,
      textDe: "Kannst du mit geschlossenen Augen sicher auf einem Bein stehen?",
      textEn: "Can you stand safely on one leg with your eyes closed?",
      reflexes: [_r.moro, _r.flr, _r.tlr, _r.atnr, _r.righting, _r.babinski],
      polarity: ReflexItemPolarity.inverse,
      requiresFilters: {ApplicabilityFilter.afterSafetyCleared},
      approvalStatus: ReflexContentApprovalStatus.expertPending,
    ),
  ],
);

class _AdultReflexRefs {
  const _AdultReflexRefs();

  PrimitiveReflex get flr => PrimitiveReflex.flr;
  PrimitiveReflex get moro => PrimitiveReflex.moro;
  PrimitiveReflex get spinalGalant => PrimitiveReflex.spinalGalant;
  PrimitiveReflex get tlr => PrimitiveReflex.tlr;
  PrimitiveReflex get atnr => PrimitiveReflex.atnr;
  PrimitiveReflex get stnr => PrimitiveReflex.stnr;
  PrimitiveReflex get landau => PrimitiveReflex.landau;
  PrimitiveReflex get babinski => PrimitiveReflex.babinski;
  PrimitiveReflex get babkin => PrimitiveReflex.babkin;
  PrimitiveReflex get plantar => PrimitiveReflex.plantar;
  PrimitiveReflex get palmar => PrimitiveReflex.palmar;
  PrimitiveReflex get righting => PrimitiveReflex.righting;
  PrimitiveReflex get rootingSucking => PrimitiveReflex.rootingSucking;
  PrimitiveReflex get amphibian => PrimitiveReflex.amphibian;
}

ReflexQuestion _filter(
  String id,
  int number, {
  required String textDe,
  required String textEn,
  required ApplicabilityFilter providesFilter,
}) {
  return ReflexQuestion(
    id: id,
    number: number,
    module: ReflexQuestionModule.other,
    adultModule: AdultQuestionModule.lifeContext,
    textDe: textDe,
    textEn: textEn,
    answerType: ReflexAnswerType.yesNoUnknown,
    role: ReflexQuestionRole.context,
    providesFilter: providesFilter,
    approvalStatus: ReflexContentApprovalStatus.expertPending,
  );
}

ReflexQuestion _score(
  String id,
  int number,
  AdultQuestionModule adultModule, {
  required String textDe,
  required String textEn,
  required List<PrimitiveReflex> reflexes,
  ReflexItemPolarity polarity = ReflexItemPolarity.direct,
  Set<ApplicabilityFilter> requiresFilters = const {},
  ReflexContentApprovalStatus approvalStatus =
      ReflexContentApprovalStatus.approved,
}) {
  return ReflexQuestion(
    id: id,
    number: number,
    module: ReflexQuestionModule.other,
    adultModule: adultModule,
    textDe: textDe,
    textEn: textEn,
    answerType: ReflexAnswerType.yesNoUnknownNotApplicable,
    role: ReflexQuestionRole.score,
    reflexes: reflexes,
    polarity: polarity,
    requiresFilters: requiresFilters,
    approvalStatus: approvalStatus,
  );
}

ReflexQuestion _contextItem(
  String id,
  int number,
  AdultQuestionModule adultModule, {
  required String textDe,
  required String textEn,
  Set<ApplicabilityFilter> requiresFilters = const {},
  ReflexContentApprovalStatus approvalStatus =
      ReflexContentApprovalStatus.approved,
}) {
  return ReflexQuestion(
    id: id,
    number: number,
    module: ReflexQuestionModule.other,
    adultModule: adultModule,
    textDe: textDe,
    textEn: textEn,
    answerType: ReflexAnswerType.yesNoUnknownNotApplicable,
    role: ReflexQuestionRole.context,
    requiresFilters: requiresFilters,
    approvalStatus: approvalStatus,
  );
}

ReflexQuestion _safety(
  String id,
  int number, {
  required String textDe,
  required String textEn,
  List<PrimitiveReflex> reflexes = const [],
  ReflexWarningRule warningRule = ReflexWarningRule.none,
  Set<ApplicabilityFilter> requiresFilters = const {},
  ReflexContentApprovalStatus approvalStatus =
      ReflexContentApprovalStatus.approved,
}) {
  return ReflexQuestion(
    id: id,
    number: number,
    module: ReflexQuestionModule.other,
    adultModule: AdultQuestionModule.safety,
    textDe: textDe,
    textEn: textEn,
    answerType: ReflexAnswerType.yesNoUnknownNotApplicable,
    role: ReflexQuestionRole.safety,
    reflexes: reflexes,
    warningRule: warningRule,
    requiresFilters: requiresFilters,
    approvalStatus: approvalStatus,
  );
}

ReflexQuestion _movement(
  String id,
  int number, {
  required String textDe,
  required String textEn,
  required List<PrimitiveReflex> reflexes,
  ReflexItemPolarity polarity = ReflexItemPolarity.inverse,
  Set<ApplicabilityFilter> requiresFilters = const {},
  ReflexContentApprovalStatus approvalStatus =
      ReflexContentApprovalStatus.expertPending,
}) {
  return ReflexQuestion(
    id: id,
    number: number,
    module: ReflexQuestionModule.other,
    adultModule: AdultQuestionModule.movementOptional,
    textDe: textDe,
    textEn: textEn,
    answerType: ReflexAnswerType.yesNoUnknownNotApplicable,
    role: ReflexQuestionRole.movement,
    reflexes: reflexes,
    polarity: polarity,
    requiresFilters: requiresFilters,
    approvalStatus: approvalStatus,
  );
}
