import 'reflex_questionnaire.dart';

final childParentQuestionnaireV1 = ReflexQuestionnaireDefinition(
  id: 'child_parent_reflex_profile',
  version: 'child_parent_v2_2026_05',
  type: ReflexQuestionnaireType.childParentReport,
  title: 'Reflexprofil für Kinder',
  scoring: const ReflexScoringDefinition(
    strongPercent: 100,
    elevatedPercent: 80,
    indicationPercent: 50,
  ),
  questions: [
    _q(1, m.pregnancyBirth,
        'Gab es während der Schwangerschaft gesundheitliche Probleme?',
        reflexes: [r.delay, r.flr, r.moro]),
    _q(2, m.pregnancyBirth,
        'Hattest du während der Schwangerschaft persönliche Probleme?',
        reflexes: [r.delay, r.flr, r.moro]),
    _q(3, m.pregnancyBirth,
        'Musstest du während der Schwangerschaft lange liegen?',
        reflexes: [r.delay]),
    _context(4, m.pregnancyBirth, 'Gab es Schwierigkeiten bei der Geburt?'),
    _q(5, m.pregnancyBirth, 'Lag dein Kind bei der Geburt in Beckenendlage?',
        reflexes: [r.flr, r.moro, r.spinalGalant, r.atnr, r.stnr]),
    _q(6, m.pregnancyBirth, 'Wurde dein Kind zu früh geboren? (Bsp.: Frühchen)',
        reflexes: [r.delay]),
    _q(7, m.pregnancyBirth, 'Gab es einen Notkaiserschnitt?',
        reflexes: [r.spinalGalant, r.atnr]),
    _q(8, m.pregnancyBirth,
        'Wurde dein Kind durch einen Wunschkaiserschnitt geboren?',
        reflexes: [r.spinalGalant, r.atnr]),
    _q(9, m.pregnancyBirth,
        'War der Geburtsvorgang ungewöhnlich kurz? (Bsp.: Sturzgeburt)',
        reflexes: [r.spinalGalant, r.atnr, r.stnr]),
    _q(10, m.pregnancyBirth, 'War der Geburtsvorgang ungewöhnlich lang?',
        reflexes: [r.atnr, r.stnr]),
    _q(11, m.pregnancyBirth,
        'Gab es während der Geburt wehenfördernde Maßnahmen?',
        reflexes: [r.spinalGalant, r.atnr, r.stnr]),
    _q(12, m.pregnancyBirth,
        'Bekamst du während der Geburt wehenhemmende Medikamente?',
        reflexes: [r.flr, r.moro, r.spinalGalant, r.atnr, r.stnr]),
    _q(13, m.posturePerception,
        'Lag dein Kind in den ersten Monaten überwiegend auf dem Rücken?',
        reflexes: [r.landau]),
    _q(14, m.posturePerception,
        'Steht dein Kind oft mit nach innen gedrehten Füßen da?',
        reflexes: [r.flr, r.babinski]),
    _q(15, m.posturePerception, 'Leidet dein Kind unter Nackenverspannungen?',
        reflexes: [r.tlr, r.landau, r.babkin]),
    _q(16, m.posturePerception,
        'Wenn sich dein Kind in Bauchlage auf die Unterarme stützt, den Oberkörper und Kopf anhebt, faustet es dann die Hände?',
        reflexes: [r.babkin, r.palmar, r.righting]),
    _q(17, m.posturePerception, 'Rollt dein Kind die Zehen immer wieder ein?',
        reflexes: [r.plantar]),
    _q(18, m.posturePerception,
        'Kann dein Kind mind. 10 Sekunden auf einem Bein stehen?',
        reflexes: [r.moro, r.tlr, r.atnr, r.babinski]),
    _q(19, m.posturePerception,
        'Kann dein Kind mind. 10 Sekunden mit geschlossenen Augen auf einem Bein stehen?',
        reflexes: [r.moro, r.tlr, r.atnr, r.babinski]),
    _q(20, m.posturePerception,
        'Sitzt dein Kind gerne auf einem oder beiden Füßen?',
        reflexes: [r.stnr]),
    _q(21, m.posturePerception,
        'Schlingt dein Kind beim Sitzen seine Beine um die Stuhlbeine?',
        reflexes: [r.stnr]),
    _q(22, m.posturePerception,
        'Neigt dein Kind den Kopf oft nach unten, der Blick geht aber von unten nach oben? (Misstrauischer Blick)',
        reflexes: [r.stnr],
        helpText:
            'Gemeint ist die beobachtbare Kopf- und Blickhaltung, nicht eine Bewertung des Verhaltens.'),
    _q(23, m.posturePerception,
        'Hat dein Kind seinen Kopf oft nach oben geneigt, schaut aber von oben herab? (Hochnäsiger Blick)',
        reflexes: [r.stnr],
        helpText:
            'Gemeint ist die beobachtbare Kopf- und Blickhaltung, nicht eine Bewertung des Verhaltens.'),
    _q(24, m.posturePerception,
        'Hat dein Kind Schwierigkeiten, über längere Zeit still zu sitzen?',
        reflexes: [r.spinalGalant, r.stnr]),
    _q(25, m.posturePerception,
        'Lehnt sich dein Kind kaum oder selten an den Stuhllehnen an?',
        reflexes: [r.spinalGalant]),
    _context(26, m.posturePerception, 'Sitzt dein Kind häufig im W-Sitz'),
    _q(27, m.posturePerception,
        'Ist dein Kind übermäßig kitzelig an den Füßen?',
        reflexes: [r.babinski]),
    _q(28, m.posturePerception, 'Ist dein Kind übermäßig kitzelig am Körper?',
        reflexes: [r.spinalGalant]),
    _q(29, m.posturePerception, 'Hat dein Kind X-Beine?',
        reflexes: [r.babinski]),
    _q(30, m.posturePerception, 'Hat dein Kind O-Beine?',
        reflexes: [r.babinski]),
    _q(31, m.motorSkills, 'Hat dein Kind das Krabbeln ausgelassen?',
        reflexes: [r.stnr]),
    _context(32, m.motorSkills, 'Wenn nein, ab wann ist dein Kind gekrabbelt?',
        answerType: ReflexAnswerType.monthsNumber, followUpOf: 'q031'),
    _context(33, m.motorSkills, 'Wann ist dein Kind das erste Mal gelaufen?',
        answerType: ReflexAnswerType.monthsNumber),
    _q(34, m.motorSkills,
        'Neigt dein Kind dazu, auf den Zehenspitzen zu gehen?',
        reflexes: [r.tlr, r.stnr, r.landau, r.plantar]),
    _q(35, m.motorSkills, 'Hat dein Kind einen schiefen Gang?',
        reflexes: [r.spinalGalant]),
    _q(36, m.motorSkills,
        'Fällt es deinem Kind schwer, eine feste Faust zu machen?',
        reflexes: [r.babkin]),
    _q(37, m.motorSkills, 'Zieht dein Kind Strümpfe und Schuhe umständlich an?',
        reflexes: [r.plantar]),
    _q(38, m.motorSkills,
        'Stützt dein Kind beim Sitzen am Tisch häufig den Kopf mit einem oder beiden Armen ab?',
        reflexes: [r.tlr, r.stnr, r.landau]),
    _q(39, m.motorSkills,
        'Räkelt und streckt sich dein Kind häufig beim Sitzen (Kopf nach hinten, Beine nach vorne)?',
        reflexes: [r.tlr, r.stnr]),
    _q(40, m.motorSkills, 'Hat dein Kind Probleme, einen Ball zu fangen?',
        reflexes: [r.moro, r.tlr, r.stnr]),
    _q(41, m.motorSkills,
        'Hat oder hatte dein Kind Probleme beim Schwimmenlernen, vor allem beim Brustschwimmen?',
        reflexes: [r.stnr, r.landau]),
    _q(42, m.motorSkills,
        'Kann sich dein Kind schlecht oder gar nicht orientieren?',
        reflexes: [r.tlr, r.atnr]),
    _q(43, m.behaviorEmotion,
        'War dein Kind in den ersten Monaten ein Schreikind?',
        reflexes: [r.delay, r.flr, r.moro, r.landau]),
    _q(44, m.behaviorEmotion, 'Ist dein Kind sehr empfindlich auf Geräusche?',
        reflexes: [r.flr, r.moro]),
    _q(45, m.behaviorEmotion,
        'Ist dein Kind sehr empfindlich auf Licht oder Helligkeit?',
        reflexes: [r.flr, r.moro]),
    _q(46, m.behaviorEmotion, 'Ist dein Kind sehr empfindlich auf Berührung?',
        reflexes: [r.flr, r.moro]),
    _q(47, m.behaviorEmotion, 'Ist dein Kind überdurchschnittlich ängstlich?',
        reflexes: [r.flr, r.moro]),
    _q(48, m.behaviorEmotion, 'Leidet dein Kind unter Trennungsangst?',
        reflexes: [r.flr, r.moro]),
    _q(49, m.behaviorEmotion, 'Ist dein Kind oft weinerlich?',
        reflexes: [r.moro]),
    _q(50, m.behaviorEmotion,
        'Ist dein Kind leicht reizbar bzw. schnell wütend?',
        reflexes: [r.moro, r.atnr]),
    _q(51, m.behaviorEmotion, 'Wirkt dein Kind oft unorganisiert?',
        reflexes: [r.spinalGalant]),
    _q(52, m.behaviorEmotion, 'Ist dein Kind oft vergesslich?',
        reflexes: [r.spinalGalant]),
    _q(53, m.behaviorEmotion, 'Liebt dein Kind Routine?', reflexes: [r.moro]),
    _q(54, m.behaviorEmotion, 'Ist dein Kind gerne in einer Fantasiewelt?',
        reflexes: [r.moro],
        helpText:
            'Gemeint ist nicht normales Fantasiespiel, sondern ein starkes Zurückziehen in Fantasie oder Tagträume, wenn dadurch Alltagssituationen schwerer gelingen.'),
    _q(55, m.behaviorEmotion, 'Steht sich dein Kind häufig selbst im Weg?',
        reflexes: [r.moro],
        helpText:
            'Gemeint ist z. B., dass dein Kind bei bekannten Aufgaben blockiert wirkt, sich schwer organisiert, vermeidet oder durch Unsicherheit, Frust oder Durcheinander ausgebremst wird.'),
    _q(56, m.behaviorEmotion, 'Ist dein Kind leicht ablenkbar?',
        reflexes: [r.moro]),
    _q(57, m.behaviorEmotion, 'Hat dein Kind ADHS oder ADS?',
        reflexes: [r.flr, r.moro, r.spinalGalant, r.tlr, r.landau, r.babinski],
        trainerFlagLabel: 'ADHS / ADS'),
    _context(
        58, m.behaviorEmotion, 'Hat dein Kind ein erhöhtes Schmerzempfinden?'),
    _context(
        59, m.behaviorEmotion, 'Hat dein Kind ein geringes Schmerzempfinden?'),
    _q(60, m.speech, 'Trägt oder trug dein Kind eine Zahnspange?',
        reflexes: [r.babkin, r.rootingSucking]),
    _q(61, m.speech,
        'Hat dein Kind eine deutliche Zahnfehlstellung oder einen gotischen Gaumen?',
        reflexes: [r.babkin, r.rootingSucking]),
    _q(62, m.speech, 'Knirscht dein Kind mit den Zähnen?',
        reflexes: [r.babkin]),
    _q(63, m.speech,
        'Hat dein Kind sehr lange am Daumen gelutscht oder einen Schnuller gehabt?',
        reflexes: [r.babkin, r.rootingSucking]),
    _q(64, m.speech, 'Hat dein Kind einen übermäßig starken Speichelfluss?',
        reflexes: [r.babkin, r.rootingSucking]),
    _q(65, m.speech,
        'Macht dein Kind beim Schreiben oder Malen Mundbewegungen?',
        reflexes: [r.babkin, r.plantar, r.palmar]),
    _q(66, m.speech,
        'Beißt dein Kind oft die Zähne fest zusammen, besonders wenn es sich konzentriert?',
        reflexes: [r.babkin, r.plantar, r.palmar]),
    _q(67, m.speech,
        'Spricht dein Kind eher undeutlich (z. B. Nuscheln, falsche Aussprache von Lauten)?',
        reflexes: [r.stnr, r.babkin, r.plantar, r.palmar, r.rootingSucking]),
    _q(68, m.speech,
        'Neigt dein Kind zur Schwatzhaftigkeit bzw. redet es unablässig?',
        reflexes: [r.spinalGalant]),
    _q(69, m.drawingWriting, 'Hält dein Kind den Stift verkrampft?',
        reflexes: [r.babkin, r.palmar, r.righting]),
    _q(70, m.drawingWriting,
        'Hält dein Kind den Stift beim Malen oder Schreiben in einer Faust?',
        reflexes: [r.babkin, r.palmar]),
    _q(71, m.drawingWriting,
        'Drückt dein Kind den Stift beim Schreiben oder Malen sehr stark auf?',
        reflexes: [r.palmar, r.righting]),
    _q(72, m.drawingWriting,
        'Hat dein Kind wenig Lust zu malen oder schreiben?',
        reflexes: [r.stnr, r.palmar, r.righting]),
    _q(73, m.drawingWriting,
        'Ermüdet dein Kind sehr schnell beim Malen oder Schreiben?',
        reflexes: [r.stnr, r.palmar, r.righting]),
    _q(74, m.drawingWriting,
        'Verdreht dein Kind Buchstaben, wie zum Beispiel b und d?',
        reflexes: [r.tlr, r.stnr]),
    _q(75, m.drawingWriting, 'Schreibt dein Kind in Spiegelschrift?',
        reflexes: [r.tlr, r.stnr]),
    _q(76, m.drawingWriting,
        'Hat dein Kind ein gutes mündliches Wissen, kann es aber nicht aufs Papier bringen?',
        reflexes: [r.stnr, r.babkin]),
    _q(77, m.drawingWriting,
        'Hat dein Kind eine unleserliche Schrift, vor allem bei der Schreibschrift?',
        reflexes: [r.spinalGalant, r.stnr, r.babkin, r.righting]),
    _q(78, m.drawingWriting,
        'Legt dein Kind beim Malen oder Schreiben das Blatt im 90-Grad-Winkel vor sich?',
        reflexes: [r.atnr]),
    _q(79, m.drawingWriting,
        'Fällt es deinem Kind schwer, die Linien beim Schreiben einzuhalten?',
        reflexes: [r.atnr]),
    _q(80, m.school,
        'Hat dein Kind Angst vor der Schule (Bauchschmerzen, Übelkeit etc.)?',
        reflexes: [r.flr, r.moro]),
    _q(81, m.school,
        'Hat dein Kind Schwierigkeiten, von der Tafel abzuschreiben (langsam, anstrengend etc.)?',
        reflexes: [r.tlr]),
    _q(82, m.school, 'Arbeitet dein Kind eher zu langsam?', reflexes: [r.tlr]),
    _q(83, m.school, 'Hat dein Kind Schwierigkeiten in der Rechtschreibung?',
        reflexes: [r.tlr, r.atnr, r.stnr, r.righting]),
    _q(84, m.school, 'Hat dein Kind Schwierigkeiten in der Grammatik?',
        reflexes: [r.tlr, r.atnr, r.stnr]),
    _q(85, m.school, 'Hat dein Kind Schwierigkeiten im Rechnen?',
        reflexes: [r.tlr, r.atnr, r.stnr]),
    _q(86, m.school, 'Ist dein Kind schlecht im Diktat?',
        reflexes: [r.flr, r.stnr]),
    _q(87, m.school, 'Hat dein Kind eine Lese-Rechtschreibschwäche?',
        reflexes: [
          r.flr,
          r.moro,
          r.tlr,
          r.atnr,
          r.stnr,
          r.babkin,
          r.plantar,
          r.palmar,
          r.righting,
          r.rootingSucking
        ]),
    _q(88, m.school, 'Hat dein Kind Dyskalkulie?',
        helpText:
            'Dyskalkulie ist eine Rechenschwäche, bei der das Verstehen von Zahlen und mathematischen Zusammenhängen trotz normaler Intelligenz dauerhaft schwerfällt. Im Alltag zeigt sich das z. B. durch: Schwierigkeiten beim Wechselgeld zählen, Uhr lesen, Zahlen merken, Mengen schätzen oder bei einfachen Rechenaufgaben immer wieder neu anfangen müssen.',
        reflexes: [
          r.flr,
          r.moro,
          r.tlr,
          r.atnr,
          r.stnr,
          r.babkin,
          r.plantar,
          r.palmar,
          r.righting,
          r.rootingSucking
        ]),
    _q(89, m.school,
        'Lässt dein Kind beim Lesen oft Buchstaben oder Wörter aus?',
        reflexes: [r.flr, r.stnr]),
    _q(90, m.school, 'Ermüdet dein Kind schnell beim Lesen?',
        reflexes: [r.flr, r.moro, r.stnr]),
    _q(91, m.school,
        'Hat dein Kind Leseschwierigkeiten (z. B. zu langsam, Wörter auslassen etc.)?',
        reflexes: [r.flr, r.atnr, r.stnr]),
    _q(92, m.school,
        'Kann dein Kind gut vorlesen, weiß aber nicht, was es vorgelesen hat?',
        reflexes: [r.flr, r.spinalGalant, r.atnr]),
    _q(93, m.school, 'Hat dein Kind Lernschwierigkeiten?', reflexes: [
      r.flr,
      r.moro,
      r.spinalGalant,
      r.tlr,
      r.atnr,
      r.stnr,
      r.landau,
      r.babinski,
      r.babkin,
      r.plantar,
      r.palmar,
      r.righting,
      r.rootingSucking
    ]),
    _q(94, m.school, 'Kann sich dein Kind schlecht konzentrieren?',
        reflexes: [r.flr, r.moro, r.landau]),
    _q(95, m.other, 'Fragt dein Kind oft nach oder sagt oft "was"?',
        reflexes: [r.tlr, r.atnr, r.stnr]),
    _q(96, m.other, 'Leidet dein Kind unter Reiseübelkeit?',
        reflexes: [r.flr, r.moro, r.tlr]),
    _q(97, m.other,
        'Hat dein Kind mit 5 Jahren oder später noch nachts eingenässt?',
        reflexes: [r.spinalGalant]),
    _q(98, m.other,
        'Hat dein Kind mit 5 Jahren oder später noch tagsüber eingenässt?',
        reflexes: [r.spinalGalant]),
    _q(99, m.other, 'Mag dein Kind keine enge Kleidung?',
        reflexes: [r.spinalGalant]),
    _q(100, m.other, 'Trägt dein Kind eine Brille?',
        reflexes: [r.flr, r.tlr, r.atnr, r.stnr]),
    _context(101, m.other, 'Schielt dein Kind?'),
    _q(102, m.other, 'Hat dein Kind ein schlechtes Zeitgefühl?',
        reflexes: [r.tlr]),
    _q(103, m.other, 'Leidet dein Kind an Asthma?', reflexes: [r.flr, r.moro]),
    _q(104, m.other, 'Leidet dein Kind an Allergien?',
        reflexes: [r.flr, r.moro]),
    _q(105, m.other, 'Leidet dein Kind an häufigen Infekten?',
        reflexes: [r.flr, r.moro]),
    _warning(106, 'Hat dein Kind Epilepsie?', 'Epilepsie', reflexes: [r.flr]),
    _warning(
        107,
        'Wurde bei deinem Kind eine Autismus-Spektrum-Diagnose gestellt oder befindet sich dies in Abklärung?',
        'Autismus-Spektrum-Diagnose',
        reflexes: [r.flr]),
    _warning(108, 'Hat dein Kind Trisomie 21 (Downsyndrom)?',
        'Trisomie 21 / Downsyndrom'),
    _warning(
        109,
        'Ist dein Kind in psychologischer oder psychiatrischer Behandlung?',
        'Psychologische / psychiatrische Behandlung',
        reflexes: [r.flr, r.moro]),
  ],
);

final demoChildShortQuestionnaireV1 = ReflexQuestionnaireDefinition(
  id: 'demo_child_short_reflex_profile',
  version: 'demo_child_short_v2_2026_05',
  type: ReflexQuestionnaireType.demoChildShort,
  title: 'Reflexprofil Kurztest',
  scoring: const ReflexScoringDefinition(
    strongPercent: 100,
    elevatedPercent: 80,
    indicationPercent: 50,
  ),
  questions: [
    _demo('demo_delay', 6, m.pregnancyBirth,
        'Wurde dein Kind zu früh geboren? (Bsp.: Frühchen)', [r.delay]),
    _demo('demo_flr', 47, m.behaviorEmotion,
        'Ist dein Kind überdurchschnittlich ängstlich?', [r.flr, r.moro]),
    _demo('demo_moro', 56, m.behaviorEmotion, 'Ist dein Kind leicht ablenkbar?',
        [r.moro]),
    _demo('demo_spinal_galant', 35, m.motorSkills,
        'Hat dein Kind einen schiefen Gang?', [r.spinalGalant]),
    _demo('demo_tlr', 81, m.school,
        'Hat dein Kind Schwierigkeiten, von der Tafel abzuschreiben?', [r.tlr]),
    _demo(
        'demo_atnr',
        79,
        m.drawingWriting,
        'Fällt es deinem Kind schwer, die Linien beim Schreiben einzuhalten?',
        [r.atnr]),
    _demo('demo_stnr', 31, m.motorSkills,
        'Hat dein Kind das Krabbeln ausgelassen?', [r.stnr]),
    _demo(
        'demo_landau',
        41,
        m.motorSkills,
        'Hat oder hatte dein Kind Probleme beim Schwimmenlernen, besonders beim Brustschwimmen?',
        [r.stnr, r.landau]),
    _demo('demo_babinski', 27, m.posturePerception,
        'Ist dein Kind übermäßig kitzelig an den Füßen?', [r.babinski]),
    _demo('demo_babkin', 62, m.speech, 'Knirscht dein Kind mit den Zähnen?',
        [r.babkin]),
    _demo('demo_plantar', 37, m.motorSkills,
        'Zieht dein Kind Strümpfe und Schuhe umständlich an?', [r.plantar]),
    _demo(
        'demo_palmar',
        71,
        m.drawingWriting,
        'Drückt dein Kind den Stift beim Schreiben oder Malen sehr stark auf?',
        [r.palmar, r.righting]),
    _demo(
        'demo_righting',
        73,
        m.drawingWriting,
        'Ermüdet dein Kind sehr schnell beim Malen oder Schreiben?',
        [r.stnr, r.palmar, r.righting]),
    _demo(
        'demo_rooting_sucking',
        64,
        m.speech,
        'Hat dein Kind einen übermäßig starken Speichelfluss?',
        [r.babkin, r.rootingSucking]),
  ],
);

const m = _ModuleRefs();
const r = _ReflexRefs();

class _ModuleRefs {
  const _ModuleRefs();

  ReflexQuestionModule get pregnancyBirth =>
      ReflexQuestionModule.pregnancyBirth;
  ReflexQuestionModule get posturePerception =>
      ReflexQuestionModule.posturePerception;
  ReflexQuestionModule get motorSkills => ReflexQuestionModule.motorSkills;
  ReflexQuestionModule get behaviorEmotion =>
      ReflexQuestionModule.behaviorEmotion;
  ReflexQuestionModule get speech => ReflexQuestionModule.speech;
  ReflexQuestionModule get drawingWriting =>
      ReflexQuestionModule.drawingWriting;
  ReflexQuestionModule get school => ReflexQuestionModule.school;
  ReflexQuestionModule get other => ReflexQuestionModule.other;
}

class _ReflexRefs {
  const _ReflexRefs();

  PrimitiveReflex get delay => PrimitiveReflex.delay;
  PrimitiveReflex get flr => PrimitiveReflex.flr;
  PrimitiveReflex get moro => PrimitiveReflex.moro;
  PrimitiveReflex get spinalGalant => PrimitiveReflex.spinalGalant;
  PrimitiveReflex get tlr => PrimitiveReflex.tlr;
  PrimitiveReflex get atnr => PrimitiveReflex.atnr;
  PrimitiveReflex get stnr => PrimitiveReflex.stnr;
  PrimitiveReflex get landau => PrimitiveReflex.landau;
  PrimitiveReflex get babinski => PrimitiveReflex.babinski;
  PrimitiveReflex get babkin => PrimitiveReflex.babkin;
  PrimitiveReflex get plantar => PrimitiveReflex.plantar;
  PrimitiveReflex get palmar => PrimitiveReflex.palmar;
  PrimitiveReflex get righting => PrimitiveReflex.righting;
  PrimitiveReflex get rootingSucking => PrimitiveReflex.rootingSucking;
}

ReflexQuestion _q(
  int number,
  ReflexQuestionModule module,
  String text, {
  List<PrimitiveReflex> reflexes = const [],
  String? helpText,
  String? trainerFlagLabel,
}) {
  return ReflexQuestion(
    id: _questionId(number),
    number: number,
    module: module,
    text: text,
    answerType: ReflexAnswerType.yesNoUnknown,
    reflexes: reflexes,
    helpText: helpText,
    trainerFlagLabel: trainerFlagLabel,
  );
}

ReflexQuestion _context(
  int number,
  ReflexQuestionModule module,
  String text, {
  ReflexAnswerType answerType = ReflexAnswerType.yesNoUnknown,
  String? followUpOf,
}) {
  return ReflexQuestion(
    id: _questionId(number),
    number: number,
    module: module,
    text: text,
    answerType: answerType,
    role: ReflexQuestionRole.context,
    followUpOf: followUpOf,
  );
}

ReflexQuestion _warning(
  int number,
  String text,
  String trainerFlagLabel, {
  List<PrimitiveReflex> reflexes = const [],
}) {
  return ReflexQuestion(
    id: _questionId(number),
    number: number,
    module: ReflexQuestionModule.other,
    text: text,
    answerType: ReflexAnswerType.yesNoUnknown,
    role:
        reflexes.isEmpty ? ReflexQuestionRole.safety : ReflexQuestionRole.score,
    reflexes: reflexes,
    warningRule: ReflexWarningRule.professionalClearanceRequired,
    trainerFlagLabel: trainerFlagLabel,
  );
}

ReflexQuestion _demo(
  String id,
  int sourceNumber,
  ReflexQuestionModule module,
  String text,
  List<PrimitiveReflex> reflexes,
) {
  return ReflexQuestion(
    id: id,
    number: sourceNumber,
    module: module,
    text: text,
    answerType: ReflexAnswerType.yesNoUnknown,
    reflexes: reflexes,
  );
}

String _questionId(int number) => 'q${number.toString().padLeft(3, '0')}';
