-- Single-use trainer invite codes.
-- Each code is generated by an admin, sent to the intended trainer,
-- and invalidated after first use. Replaces the shared TRAINER_CODE secret.

-- Safely extend role constraint to include 'admin'.
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'profiles_role_check'
  ) THEN
    ALTER TABLE public.profiles DROP CONSTRAINT profiles_role_check;
  END IF;
  ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check
    CHECK (role IN ('practitioner', 'trainer', 'admin'));
END $$;

-- Trainer invite codes table.
CREATE TABLE IF NOT EXISTS public.trainer_invite_codes (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  code        TEXT        UNIQUE NOT NULL,
  created_by  UUID        NOT NULL REFERENCES public.profiles(id),
  used_by     UUID        REFERENCES public.profiles(id),
  used_at     TIMESTAMPTZ,
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_trainer_invite_codes_code
  ON public.trainer_invite_codes(code);
CREATE INDEX IF NOT EXISTS idx_trainer_invite_codes_created_by
  ON public.trainer_invite_codes(created_by);

ALTER TABLE public.trainer_invite_codes ENABLE ROW LEVEL SECURITY;

-- Admins can read all codes.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'trainer_invite_codes'
      AND policyname = 'trainer_invite_codes_admin_select'
      AND schemaname = 'public'
  ) THEN
    CREATE POLICY trainer_invite_codes_admin_select
      ON public.trainer_invite_codes FOR SELECT
      USING (
        EXISTS (
          SELECT 1 FROM public.profiles
          WHERE id = auth.uid() AND role = 'admin'
        )
      );
  END IF;
END $$;

-- INSERT and UPDATE are service-role only (Edge Functions).
-- No policy = blocked for authenticated users.

-- Grant admin@corejourney.dev the admin role if the account already exists.
DO $$
DECLARE
  v_user_id UUID;
BEGIN
  SELECT id INTO v_user_id
  FROM auth.users
  WHERE email = 'admin@corejourney.dev'
  LIMIT 1;

  IF v_user_id IS NOT NULL THEN
    UPDATE public.profiles SET role = 'admin' WHERE id = v_user_id;
  END IF;
END $$;
